name: Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev-mode-protection:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for dev mode bypasses
      run: |
        # Check that all sendBeacon calls are properly protected by dev mode checks
        sendbeacon_lines=$(grep -rn "navigator\.sendBeacon" src/ || true)
        if [ -n "$sendbeacon_lines" ]; then
          echo "Found sendBeacon calls:"
          echo "$sendbeacon_lines"
          
          # Check each sendBeacon call has proper dev mode protection
          while IFS= read -r line; do
            file=$(echo "$line" | cut -d: -f1)
            lineno=$(echo "$line" | cut -d: -f2)
            
            # Check if there's a "if (!devMode)" within 10 lines before this sendBeacon call
            if ! sed -n "$((lineno-10)),$((lineno-1))p" "$file" 2>/dev/null | grep -q "if.*!devMode"; then
              echo "❌ CRITICAL: sendBeacon call at $file:$lineno not protected by dev mode check!"
              exit 1
            fi
          done <<< "$sendbeacon_lines"
          
          echo "✅ All sendBeacon calls properly protected by dev mode checks"
        fi
        
    - name: Validate webhook URLs
      run: |
        if grep -r "hook\.us1\.make\.com" src/ | grep -v -E "(r1kbh1gkk5j31prdnhcn1dq8hsk2gyd9|sdv55xk1d8iacpxbhnagymcgrkuf6ju5)"; then
          echo "❌ CRITICAL: Unauthorized webhook URL detected!"
          exit 1
        fi
        
    - name: Build check
      run: npm run build
